clear; close all;


%% Lens name and propertiesq

lensName='wideangle100deg-zemax'
offset_sensorside=0.01;     
offset_objectside=0.01; %%mm
lensThickness=6.439;

%% Load input output rays 
% load data generated by ZEMAX

X=dlmread(['/home/thomas42/Downloads/wideangle100deg_mm.txt'],'\s',1);



% Extract input and output rays
iRays=X(:,[3 5 6]);
oRays=X(:,[8 9 10 11 12 13]);


%% RTF generation options
for polyDeg = [3 4 5 6 7 8 9 10]
outputDir = fullfile(piRootPath, 'data/lens/RTF');
%outputDir='./'
visualize=true;

%% generateRTF
rtfName = [lensName '-poly' num2str(polyDeg) '-raytransfer'];
rtf=generateRTFfromIO(lensName,rtfName,iRays,oRays,offset_sensorside,offset_objectside,lensThickness,...
    'outputdir',outputDir,'visualize',visualize,'polynomialdegree',polyDeg,...
    'intersectionplanedistance',17)

end
