clear; close all;


%% Lens name and propertiesq

lensName='inversetelephoto-zemax'
offset_sensorside=0.1;
offset_objectside=0.1; %%mm
lensThickness=1.30140;

%% Load input output rays 
% load data generated by ZEMAX

X=dlmread(['/home/thomas42/Downloads/inversetelephoto.txt'],'\s',1);



% Extract input and output rays
iRays=X(:,[3 5 6]);
oRays=X(:,[8 9 10 11 12 13]);



% Z output values need to be calculated from rear vertex so we need to
% change coordinate system. CAUTION, whether this shift is necessary
% depends on whether ZEMAX data was generated using the rear vertex as a
% global coordinate reference. 

% For the current dataset the global coordinate reference was the input
% plane. Hence we need to subtract inputplaneoffset + lensthickness from
% the Z value of oRays

 oRays(:,3)= oRays(:,3) - (lensThickness+offset_sensorside);


%% RTF generation options
for polyDeg = [1:8]
outputDir = fullfile(piRootPath, 'data/lens/RTF');
%outputDir='./'
visualize=true;

%% generateRTF
rtfName = [lensName '-poly' num2str(polyDeg) '-raytransfer'];
rtf=generateRTFfromIO(lensName,rtfName,iRays,oRays,offset_sensorside,offset_objectside,lensThickness,...
    'outputdir',outputDir,'visualize',visualize,'polynomialdegree',polyDeg,...
    'intersectionplanedistance',17)

end
