clear; close all;


%% Lens name and propertiesq

lensName='tessar-moredata-zemax'

lensThickness=16.4;

%% Load input output rays 
% load data generated by ZEMAX

%X=dlmread(['/home/thomas42/Downloads/tessarnew.txt'],'\s',1); offset_sensorside=0.01; offset_objectside=0.01; %%mm
%X=dlmread(['/home/thomas42/Downloads/tessar_circle.txt'],'\s',1); offset_sensorside=0.01; offset_objectside=1; %%mm
%X=dlmread(['/home/thomas42/Downloads/tessar_plane.txt'],'\s',1); offset_sensorside=0.01; offset_objectside=0.01; %%mm
%X=dlmread(['/home/thomas42/Downloads/tessar-rayaim.txt'],'\s',1); offset_sensorside=0.01; offset_objectside=0.01; %%mm
%X=dlmread(['/home/thomas42/Downloads/tessar-rayaim-morerays.txt'],'\s',1); offset_sensorside=0.01; offset_objectside=0.01; %%mm
%X=dlmread(['/home/thomas42/Downloads/tessar-rayaim-novignetfactors.txt'],'\s',1); offset_sensorside=0.01; offset_objectside=0.01; %%mm


%X=dlmread(['/home/thomas42/Downloads/tessar-rayaim-novignetfactors-focalplane-planar.txt'],'\s',1); offset_sensorside=90; offset_objectside=0.01; %%mm
X=dlmread(['/home/thomas42/Downloads/tessar-rayaim-vignetremoved-moredata.txt'],'\s',1); offset_sensorside=0.01; offset_objectside=0.01; %%mm



% Extract input and output rays
iRays=X(:,[3 5 6]);
oRays=X(:,[8 9 10 11 12 13]);



% Z output values need to be calculated from rear vertex so we need to
% change coordinate system. CAUTION, whether this shift is necessary
% depends on whether ZEMAX data was generated using the rear vertex as a
% global coordinate reference. 

% For the current dataset the global coordinate reference was the input
% plane. Hence we need to subtract inputplaneoffset + lensthickness from
% the Z value of oRays
% NOT NEEDED HERE BECAUSE DATASET ALREADY REFERENCED TO REAR VERTEX
% oRays(:,3)= oRays(:,3) - (lensThickness+offset_sensorside);


%% RTF generation options
for polyDeg = 1:13
    polyDeg
outputDir = fullfile(piRootPath, 'data/lens/RTF');
%outputDir='./'
visualize=true;

%% generateRTF
rtfName = [lensName '-poly' num2str(polyDeg) '-raytransfer'];
rtf=generateRTFfromIO(lensName,rtfName,iRays,oRays,offset_sensorside,offset_objectside,lensThickness,...
    'outputdir',outputDir,'visualize',visualize,'polynomialdegree',polyDeg,...
    'intersectionplanedistance',17);
end