clear; close all;


%% Lens name and propertiesq
lensName='pixel4a-rearcamera-nondegenerate'
filmdistance_mm=0.464135918+0.2
offset_sensorside=filmdistance_mm;
offset_objectside=1.48002192; %%mm
lensThickness=4.827;

%% Load input output rays 
% load data generated by ZEMAX
X=dlmread('Gout-P4Ra_20111103.txt','\s',1);
%X=dlmread('Gout-P4Rb183050_20211115.txt','\s',1);
X=dlmread('Gout-P4Rb183050_20211204.txt','\s',1);
% Extract input and output rays
iRays=X(:,[3 5 6]);
oRays=X(:,[8 9 10 11 12 13]);


%% RTF generation options
polyDeg = 5
outputDir = fullfile(piRootPath, 'data/lens/RTF');
%outputDir='./'
visualize=true;

%% generateRTF
rtfName = [lensName '-poly' num2str(polyDeg) '-raytransfer'];
rtf=generateRTFfromIO(lensName,rtfName,iRays,oRays,offset_sensorside,offset_objectside,lensThickness,'outputdir',outputDir,'visualize',visualize,'polynomialdegree',polyDeg)
