clear; close all;


%% Lens name and propertiesq
lensName='dgauss28deg-zemax'
diaphragm_mm=2;

offset_sensorside=0.01;
offset_objectside=0.01; %%mm
lensThickness=32.04;

%% Load input output rays 
% load data generated by ZEMAX
X=dlmread(['/home/thomas42/Downloads/dgaussreverse-diaphragm' num2str(diaphragm_mm) '.txt'],'\s',1);



% Extract input and output rays
iRays=X(:,[3 5 6]);
oRays=X(:,[8 9 10 11 12 13]);


%% RTF generation options
polyDeg = 5
outputDir = fullfile(piRootPath, 'data/lens/RTF');
%outputDir='./'
visualize=true;

%% generateRTF
rtfName = [lensName '-diaphragm' num2str(diaphragm_mm) '-poly' num2str(polyDeg) '-raytransfer'];
rtf=generateRTFfromIO(lensName,rtfName,iRays,oRays,offset_sensorside,offset_objectside,lensThickness,...
    'outputdir',outputDir,'visualize',visualize,'polynomialdegree',polyDeg,...
    'intersectionplanedistance',17)
