clear; close all;


%% Lens name and propertiesq

lensName='dgauss28deg-undersample-zemax'
offset_sensorside=0.01;
offset_objectside=0.01; %%mm
lensThickness=75.67388;

%% Load input output rays 
% load data generated by ZEMAX

X=dlmread(['/home/thomas42/Downloads/dgauss28deg.txt'],'\s',1);




% Extract input and output rays
iRays=X(:,[3 5 6]);
oRays=X(:,[8 9 10 11 12 13]);

% Randomize
perm = randperm(size(iRays,1));
iRays = iRays(perm,:);
oRays = oRays(perm,:);

% Subsample
delta=2000;
iRays=iRays(1:delta:end,:);
oRays=oRays(1:delta:end,:);



%% RTF generation options
for polyDeg = 1:15
outputDir = fullfile(piRootPath, 'data/lens/RTF');
%outputDir='./'
visualize=false;

%% generateRTF
rtfName = [lensName '-delta' num2str(delta) '-poly' num2str(polyDeg) '-raytransfer'];
rtf=generateRTFfromIO(lensName,rtfName,iRays,oRays,offset_sensorside,offset_objectside,lensThickness,...
    'outputdir',outputDir,'visualize',visualize,'polynomialdegree',polyDeg,...
    'intersectionplanedistance',17)
pause(0.1)

end